spring:
  application:
    name: order
  cloud:
    config:
      discovery:
        enabled: true
      profile: dev
spring:
  datasource:
    url: jdbc:mysql://47.98.132.167/sell?characterEncoding=utf-8&useSSL=false
    username: root
    password: YaoZheng@123
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
girl:
  name: wujia
  age: 25
env: test3
